How many late days are you using for this assignment? 0 Late Days.

In [28]:
# Imports and pip installations (if needed) 
%pip install pandas numpy scikit-learn tabulate
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder, StandardScaler

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (2.2.3)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (2.2.3)
Requirement already satisfied: scikit-learn in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (1.6.1)
Requirement already satisfied: tabulate in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (0.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/txi/Library/Python/3.11/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas) (2025.1)
Requirement already satisfied: scipy>=1.6.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from scikit-learn) (1.15.2)
Requirement already satisfied: joblib>=1.2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: six>=1.5 in /Users/txi/Library/Python/3.11/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

# Part 1: Load the dataset

In [29]:
# Load the given datasets
pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')
pd.reset_option('display.expand_frame_repr')
categorical_df = pd.read_csv("chronic_kidney_disease_categorical.csv")
numerical_df = pd.read_csv("chronic_kidney_disease_numerical.csv")
#4.2 Assignment
column_mappings = {
    "age": "Age",
    "bp": "Blood Pressure",
    "sg": "Specific Gravity",
    "al": "Albumin",
    "su": "Sugar",
    "rbc": "Red Blood Cells",
    "pc": "Pus Cell",
    "pcc": "Pus Cell Clumps",
    "ba": "Bacteria",
    "bgr": "Blood Glucose Random",
    "bu": "Blood Urea",
    "sc": "Serum Creatinine",
    "sod": "Sodium",
    "pot": "Potassium",
    "hemo": "Hemoglobin",
    "pcv": "Packed Cell Volume",
    "wbcc": "White Blood Cell Count",
    "rbcc": "Red Blood Cell Count",
    "htn": "Hypertension",
    "dm": "Diabetes Mellitus",
    "cad": "Coronary Artery Disease",
    "appet": "Appetite",
    "pe": "Pedal Edema",
    "ane": "Anemia",
}
numerical_df.rename(columns=column_mappings, inplace=True)
categorical_df.rename(columns=column_mappings, inplace=True)
# Print the data
print("Categorical Data:")
print(categorical_df.head())
print(categorical_df.tail())
print("\nNumerical Data:")
print(numerical_df.head())
print(numerical_df.tail())

Categorical Data:
   unique_id  Albumin  Sugar Red Blood Cells  Pus Cell Pus Cell Clumps  \
0     224481      3.0    NaN             NaN       NaN      notpresent
1     992643      0.0    0.0             NaN       NaN      notpresent
2     308740      1.0    0.0        abnormal  abnormal      notpresent
3     450314      1.0    0.0             NaN    normal      notpresent
4     881763      0.0    0.0          normal    normal      notpresent

     Bacteria Hypertension Diabetes Mellitus Coronary Artery Disease Appetite  \
0  notpresent          yes               yes                      no     good
1  notpresent           no                no                      no     good
2  notpresent          yes                no                      no     good
3  notpresent           no                no                      no     good
4  notpresent           no                no                      no     good

  Pedal Edema Anemia  Target
0         yes     no     ckd
1          no     no  notckd
2         yes     no     ckd
3          no    yes     ckd
4          no     no  notckd
     unique_id  Albumin  Sugar Red Blood Cells  Pus Cell Pus Cell Clumps  \
425     769512      0.0    0.0          normal    normal      notpresent
426     872034      2.0    1.0        abnormal  abnormal      notpresent
427     643007      NaN    NaN             NaN    normal      notpresent
428     840392      NaN    NaN             NaN       NaN      notpresent
429     856244      0.0    0.0             NaN    normal      notpresent

       Bacteria Hypertension Diabetes Mellitus Coronary Artery Disease  \
425  notpresent           no                no                      no
426     present          yes               yes                     yes
427  notpresent          yes               yes                     yes
428  notpresent          yes                no                      no
429  notpresent          yes               yes                      no

    Appetite Pedal Edema Anemia  Target
425     good          no     no  notckd
426     poor          no     no     ckd
427     poor          no     no     ckd
428     poor          no     no     ckd
429     poor          no     no     ckd

Numerical Data:
   unique_id   Age  Blood Pressure  Blood Glucose Random  Blood Urea  \
0     203694  38.0            80.0                  99.0        19.0
1     938027  43.0            60.0                 108.0        25.0
2     421471  37.0            60.0                 111.0        35.0
3     764115  70.0            90.0                 144.0       125.0
4     240975  47.0            80.0                  95.0        35.0

   Serum Creatinine  Sodium  Potassium  Hemoglobin  Packed Cell Volume  \
0               0.5   147.0        3.5        13.6                44.0
1               1.0   144.0        5.0        17.8                43.0
2               0.8   135.0        4.1        16.2                50.0
3               4.0   136.0        4.6        12.0                37.0
4               0.9   140.0        4.1         NaN                 NaN

   White Blood Cell Count  Red Blood Cell Count
0                  7300.0                   6.4
1                  7200.0                   5.5
2                  5500.0                   5.7
3                  8200.0                   4.5
4                     NaN                   NaN
     unique_id   Age  Blood Pressure  Blood Glucose Random  Blood Urea  \
415     522912  56.0            80.0                 165.0        55.0
416     475200  64.0           100.0                 163.0        54.0
417     168242  48.0            60.0                 112.0        44.0
418     474407  21.0            90.0                 107.0        40.0
419     926033  50.0            70.0                 230.0        50.0

     Serum Creatinine  Sodium  Potassium  Hemoglobin  Packed Cell Volume  \
415               1.8     NaN        NaN        13.5                40.0
416               7.2   140.0        4.6         7.9                26.0
417               1.2   142.0        4.9        14.5                44.0
418               1.7   125.0        3.5         8.3                23.0
419               2.2     NaN        NaN        12.0                41.0

     White Blood Cell Count  Red Blood Cell Count
415                 11800.0                   5.0
416                  7500.0                   3.4
417                  9400.0                   6.4
418                 12400.0                   3.9
419                 10400.0                   4.6

# Part 2: Analyze the Dataset

Refer to this: https://archive.ics.uci.edu/dataset/336/chronic+kidney+disease

Explain what the each data is in your own words. What are the features and labels? Are the features in the given datasets : categorical, numerical or both? Give 3 examples of categorical and numerical columns each (if they exist)

Answer: The Chronic Kidney Disease dataset is essentially various clinical records where a patients data is captured and used to predict whether they have Chronic Kidney Disease (this is the label). The features are health indicators, which provide precise, quantifiable data such as lab test results, while others are categorical, representing qualitative assessments. For example, numerical features may include values like the patient’s age or specific test results, and categorical features might indicate the presence or absence of certain conditions or abnormal test findings.
• Numerical examples: Age, Blood Pressure, Serum Creatinine
• Categorical examples: Anemia (ane), Hypertension (htn), Diabetes Mellitus (dm)

# Part 3: Data Preprocessing

A fundamental skill in Machine Learning is mastering the art of data cleaning and preprocessing. In this assignment, you will learn and apply essential data cleaning techniques to transform a raw dataset into a clean, ready-to-use form which you can use for regression or classification tasks. By the end of this assignment, you'll have a fully clean dataset and a solid foundation in preparing data for various machine learning models.

## Part 3.1 : Drop Duplicate rows

Let's start by checking if the given datasets have any duplicate rows (same Unique Id). Use pandas to identify and remove these duplicate rows from the given dataset

In [30]:
# For the numerical dataset, check if there are duplicate rows in the dataset. If yes, print total number of duplicate rows
duplicate_numerical = numerical_df[numerical_df.duplicated()]
print(f"Total duplicate rows in numerical dataset: {len(duplicate_numerical)}")
print(duplicate_numerical)
# Drop these duplicate rows
numerical_df.drop_duplicates(inplace=True)
# Repeat the same for categorical dataset. Print the duplicate rows and drop them
duplicate_categorical = categorical_df[categorical_df.duplicated()]
print(f"Total duplicate rows in categorical dataset: {len(duplicate_categorical)}")
print(duplicate_categorical)
# Drop these duplicate rows
categorical_df.drop_duplicates(inplace=True)

Total duplicate rows in numerical dataset: 30
     unique_id   Age  Blood Pressure  Blood Glucose Random  Blood Urea  \
107     872034  70.0            90.0                 184.0        98.6
149     721270  58.0            70.0                 102.0        48.0
171     240975  47.0            80.0                  95.0        35.0
173     441170  79.0            80.0                 111.0        44.0
185     261137  35.0            60.0                 105.0        39.0
194     769512  38.0            60.0                  91.0        36.0
213     354223  64.0            70.0                  97.0        27.0
244     302906  59.0           100.0                   NaN        96.0
245     431871  57.0            60.0                 132.0        18.0
248     687021  52.0            80.0                  99.0        25.0
249     843449  30.0            80.0                 131.0        38.0
265     628271  65.0            90.0                 270.0        39.0
273     862719  61.0            80.0                 131.0        23.0
292     202793  74.0            60.0                 108.0        68.0
299     224481  54.0            60.0                 125.0        21.0
300     856244  75.0            80.0                 156.0        45.0
315     572140  55.0            80.0                 104.0        28.0
324     501321   4.0             NaN                  99.0        23.0
327     283427  55.0            80.0                 140.0        49.0
331     856244  75.0            80.0                 156.0        45.0
342     938027  43.0            60.0                 108.0        25.0
345     337834  48.0            70.0                 117.0        56.0
360     643007  76.0            90.0                  93.0       155.0
362     840392  47.0            80.0                 114.0        87.0
376     415906  60.0            80.0                 131.0        10.0
380     708255   3.0             NaN                   NaN        22.0
385     118191  42.0            70.0                  93.0        32.0
402     153227  60.0            90.0                 490.0        95.0
412     583971  62.0            90.0                  94.0        25.0
413     158929  73.0             NaN                  95.0        51.0

     Serum Creatinine  Sodium  Potassium  Hemoglobin  Packed Cell Volume  \
107               3.3   138.0        3.9         5.8                 NaN
149               1.2   139.0        4.3        15.0                40.0
171               0.9   140.0        4.1         NaN                 NaN
173               1.2   146.0        3.6        16.3                40.0
185               0.5   135.0        3.9        14.7                43.0
194               0.7   135.0        3.7        14.0                46.0
213               0.7   145.0        4.8        13.8                49.0
244               6.4     NaN        NaN         6.6                 NaN
245               1.1   150.0        4.7        15.4                42.0
248               0.8   135.0        3.7        15.0                52.0
249               1.0   147.0        3.8        14.1                45.0
265               2.0     NaN        NaN        12.0                36.0
273               0.8   140.0        4.1        11.3                35.0
292               1.8     NaN        NaN         NaN                 NaN
299               1.3   137.0        3.4        15.0                46.0
300               2.4   140.0        3.4        11.6                35.0
315               0.9   142.0        4.8        17.3                52.0
324               0.6   138.0        4.4        12.0                34.0
327               0.5   150.0        4.9        15.7                47.0
331               2.4   140.0        3.4        11.6                35.0
342               1.0   144.0        5.0        17.8                43.0
345               3.8   111.0        2.5        11.2                32.0
360               7.3   132.0        4.9         NaN                 NaN
362               5.2   139.0        3.7        12.1                 NaN
376               0.5   146.0        5.0        14.5                41.0
380               0.7     NaN        NaN        10.7                34.0
385               0.9   143.0        4.7        16.6                43.0
402               2.7   131.0        3.8        11.5                35.0
412               1.1   131.0        3.7         NaN                 NaN
413               1.6   142.0        3.5         NaN                 NaN

     White Blood Cell Count  Red Blood Cell Count
107                     NaN                   NaN
149                  8100.0                   4.9
171                     NaN                   NaN
173                  8000.0                   6.4
185                  5800.0                   6.2
194                  9100.0                   5.8
213                  6400.0                   4.8
244                     NaN                   NaN
245                 11000.0                   4.5
248                  6300.0                   5.3
249                  9400.0                   5.3
265                  9800.0                   4.9
273                     NaN                   NaN
292                     NaN                   NaN
299                     NaN                   NaN
300                 10300.0                   4.0
315                  8200.0                   4.8
324                     NaN                   NaN
327                  6700.0                   4.9
331                 10300.0                   4.0
342                  7200.0                   5.5
345                  6700.0                   3.9
360                     NaN                   NaN
362                     NaN                   NaN
376                 10700.0                   5.1
380                 12300.0                   NaN
385                  7100.0                   5.3
402                 12000.0                   4.5
412                     NaN                   NaN
413                     NaN                   NaN
Total duplicate rows in categorical dataset: 30
     unique_id  Albumin  Sugar Red Blood Cells  Pus Cell Pus Cell Clumps  \
231     856244      0.0    0.0             NaN    normal      notpresent
401     628271      2.0    1.0        abnormal    normal      notpresent
402     158929      1.0    0.0             NaN       NaN      notpresent
403     240975      0.0    0.0          normal    normal      notpresent
404     441170      0.0    0.0          normal    normal      notpresent
405     337834      4.0    0.0          normal  abnormal         present
406     118191      0.0    0.0          normal    normal      notpresent
407     224481      3.0    NaN             NaN       NaN      notpresent
408     302906      NaN    NaN             NaN       NaN      notpresent
409     938027      0.0    0.0          normal    normal      notpresent
410     572140      0.0    0.0          normal    normal      notpresent
411     283427      0.0    0.0          normal    normal      notpresent
412     202793      NaN    NaN             NaN       NaN      notpresent
413     501321      1.0    0.0             NaN    normal      notpresent
414     153227      3.0    5.0        abnormal    normal      notpresent
415     843449      0.0    0.0          normal    normal      notpresent
416     415906      0.0    0.0          normal    normal      notpresent
417     708255      2.0    0.0          normal    normal      notpresent
418     862719      0.0    0.0             NaN    normal      notpresent
419     354223      0.0    0.0          normal    normal      notpresent
420     721270      0.0    0.0          normal    normal      notpresent
421     687021      0.0    0.0          normal    normal      notpresent
422     583971      1.0    0.0             NaN    normal      notpresent
423     261137      0.0    0.0          normal    normal      notpresent
424     431871      0.0    0.0          normal    normal      notpresent
425     769512      0.0    0.0          normal    normal      notpresent
426     872034      2.0    1.0        abnormal  abnormal      notpresent
427     643007      NaN    NaN             NaN    normal      notpresent
428     840392      NaN    NaN             NaN       NaN      notpresent
429     856244      0.0    0.0             NaN    normal      notpresent

       Bacteria Hypertension Diabetes Mellitus Coronary Artery Disease  \
231  notpresent          yes               yes                      no
401  notpresent          yes               yes                      no
402  notpresent           no                no                      no
403  notpresent           no                no                      no
404  notpresent           no                no                      no
405  notpresent          yes                no                      no
406  notpresent           no                no                      no
407  notpresent          yes               yes                      no
408  notpresent          yes               yes                      no
409  notpresent           no                no                      no
410  notpresent           no                no                      no
411  notpresent           no                no                      no
412  notpresent          yes               yes                      no
413  notpresent           no                no                      no
414     present          yes               yes                      no
415  notpresent           no                no                      no
416  notpresent           no                no                      no
417  notpresent           no                no                      no
418  notpresent           no                no                      no
419  notpresent           no                no                      no
420  notpresent           no                no                      no
421  notpresent           no                no                      no
422  notpresent          yes                no                      no
423  notpresent           no                no                      no
424  notpresent           no                no                      no
425  notpresent           no                no                      no
426     present          yes               yes                     yes
427  notpresent          yes               yes                     yes
428  notpresent          yes                no                      no
429  notpresent          yes               yes                      no

    Appetite Pedal Edema Anemia  Target
231     poor          no     no     ckd
401     poor          no    yes     ckd
402     good          no     no     ckd
403     good          no     no  notckd
404     good          no     no  notckd
405     poor         yes    yes     ckd
406     good          no     no  notckd
407     good         yes     no     ckd
408     good          no    yes     ckd
409     good          no     no  notckd
410     good          no     no  notckd
411     good          no     no  notckd
412     good          no     no     ckd
413     good          no     no     ckd
414     good          no     no     ckd
415     good          no     no  notckd
416     good          no     no  notckd
417     good          no     no     ckd
418     good          no     no     ckd
419     good          no     no  notckd
420     good          no     no  notckd
421     good          no     no  notckd
422     good         yes    yes     ckd
423     good          no     no  notckd
424     good          no     no  notckd
425     good          no     no  notckd
426     poor          no     no     ckd
427     poor          no     no     ckd
428     poor          no     no     ckd
429     poor          no     no     ckd

## Part 3.2: Combine two differents datasets

A good skill to have is to know how to combine 2 different datasets.

Are all the unique ids are present in both datasets? Why do you think so? If not, what do the rows that are missing from one of the datasets look like in the combined table?

Answer: No, not all Unique Id's are present in both datasets. The rows that are missing from the numerical dataset would simply present in the merged table as "NaN" for all values that were supposed to be numerical. For example: 47 208034 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN notpresent notpresent yes yes yes good yes no ckd, where ALL NaN values are from the numerical dataset, where unique id 208034 is not present.

In [31]:

# Merge the two given numerical and categorical datasets based on their unique_ID.
if 'unique_id' in categorical_df.columns and 'unique_id' in numerical_df.columns:
    merged_df = pd.merge(numerical_df, categorical_df, on="unique_id", how="outer")
else:
    raise ValueError("unique_id column is missing from one of the datasets")
#Print the combined dataset
print(merged_df.head()) 
print(merged_df.tail())

   unique_id   Age  Blood Pressure  Blood Glucose Random  Blood Urea  \
0     102677  59.0            70.0                  76.0       186.0
1     103570  24.0            80.0                 125.0         NaN
2     104675  65.0            80.0                 215.0       133.0
3     105923  90.0            90.0                 139.0        89.0
4     107297  60.0            70.0                   NaN         NaN

   Serum Creatinine  Sodium  Potassium  Hemoglobin  Packed Cell Volume  ...  \
0              15.0   135.0        7.6         7.1                22.0  ...
1               NaN   136.0        3.5        15.4                43.0  ...
2               2.5     NaN        NaN        13.2                41.0  ...
3               3.0   140.0        4.1        12.0                37.0  ...
4               NaN     NaN        NaN        16.4                43.0  ...

   Pus Cell  Pus Cell Clumps    Bacteria  Hypertension Diabetes Mellitus  \
0  abnormal       notpresent  notpresent           yes                no
1    normal       notpresent  notpresent            no                no
2    normal          present  notpresent            no               yes
3    normal       notpresent  notpresent           yes               yes
4    normal       notpresent  notpresent            no                no

  Coronary Artery Disease Appetite Pedal Edema Anemia  Target
0                      no     poor         yes    yes     ckd
1                      no     good          no     no  notckd
2                      no     good          no     no     ckd
3                      no     good          no     no     ckd
4                      no     good          no     no  notckd

[5 rows x 25 columns]
     unique_id   Age  Blood Pressure  Blood Glucose Random  Blood Urea  \
395     995177  69.0            70.0                 214.0        96.0
396     996076  57.0            60.0                 105.0        49.0
397     996412  70.0            60.0                 120.0        40.0
398     997629  35.0             NaN                  99.0        30.0
399     997876  64.0            70.0                 107.0        15.0

     Serum Creatinine  Sodium  Potassium  Hemoglobin  Packed Cell Volume  ...  \
395               6.3   120.0        3.9         9.4                28.0  ...
396               1.2   150.0        4.7        15.7                44.0  ...
397               0.5   140.0        4.6        16.0                43.0  ...
398               0.5   135.0        4.9        15.4                48.0  ...
399               NaN     NaN        NaN        12.8                38.0  ...

     Pus Cell  Pus Cell Clumps    Bacteria  Hypertension Diabetes Mellitus  \
395  abnormal          present     present           yes               yes
396    normal       notpresent  notpresent            no                no
397       NaN       notpresent  notpresent            no                no
398    normal              NaN         NaN            no                no
399    normal       notpresent  notpresent            no                no

    Coronary Artery Disease Appetite Pedal Edema Anemia  Target
395                     yes     good         yes    yes     ckd
396                      no     good          no     no  notckd
397                      no     good          no     no  notckd
398                      no     good          no     no  notckd
399                      no     good          no     no     ckd

[5 rows x 25 columns]

## Part 3.3: Rows with Missing values

Removing missing values from a dataset is important for classification because it ensures the model is trained on complete and accurate data, leading to better performance and reliable predictions. Incomplete data can introduce bias and errors, negatively impacting the model's effectiveness.

In [32]:

# Count rows with at least one missing value
rows_with_missing = merged_df.shape[0] - merged_df.dropna().shape[0]
missing_percentage = (rows_with_missing / merged_df.shape[0]) * 100
# Print before dropping missing values
print(f"Percentage of rows with missing values: {missing_percentage:.2f}%")
print("Before dropping missing values:")
print(merged_df.head()) 
print(merged_df.tail()) 
# Drop rows with missing values
merged_df.dropna(inplace=True)
# Print the dataset after removing missing values
print("After dropping missing values:")
merged_df.reset_index(drop=True, inplace=True)
print(merged_df.head()) 
print(merged_df.tail())

Percentage of rows with missing values: 61.75%
Before dropping missing values:
   unique_id   Age  Blood Pressure  Blood Glucose Random  Blood Urea  \
0     102677  59.0            70.0                  76.0       186.0
1     103570  24.0            80.0                 125.0         NaN
2     104675  65.0            80.0                 215.0       133.0
3     105923  90.0            90.0                 139.0        89.0
4     107297  60.0            70.0                   NaN         NaN

   Serum Creatinine  Sodium  Potassium  Hemoglobin  Packed Cell Volume  ...  \
0              15.0   135.0        7.6         7.1                22.0  ...
1               NaN   136.0        3.5        15.4                43.0  ...
2               2.5     NaN        NaN        13.2                41.0  ...
3               3.0   140.0        4.1        12.0                37.0  ...
4               NaN     NaN        NaN        16.4                43.0  ...

   Pus Cell  Pus Cell Clumps    Bacteria  Hypertension Diabetes Mellitus  \
0  abnormal       notpresent  notpresent           yes                no
1    normal       notpresent  notpresent            no                no
2    normal          present  notpresent            no               yes
3    normal       notpresent  notpresent           yes               yes
4    normal       notpresent  notpresent            no                no

  Coronary Artery Disease Appetite Pedal Edema Anemia  Target
0                      no     poor         yes    yes     ckd
1                      no     good          no     no  notckd
2                      no     good          no     no     ckd
3                      no     good          no     no     ckd
4                      no     good          no     no  notckd

[5 rows x 25 columns]
     unique_id   Age  Blood Pressure  Blood Glucose Random  Blood Urea  \
395     995177  69.0            70.0                 214.0        96.0
396     996076  57.0            60.0                 105.0        49.0
397     996412  70.0            60.0                 120.0        40.0
398     997629  35.0             NaN                  99.0        30.0
399     997876  64.0            70.0                 107.0        15.0

     Serum Creatinine  Sodium  Potassium  Hemoglobin  Packed Cell Volume  ...  \
395               6.3   120.0        3.9         9.4                28.0  ...
396               1.2   150.0        4.7        15.7                44.0  ...
397               0.5   140.0        4.6        16.0                43.0  ...
398               0.5   135.0        4.9        15.4                48.0  ...
399               NaN     NaN        NaN        12.8                38.0  ...

     Pus Cell  Pus Cell Clumps    Bacteria  Hypertension Diabetes Mellitus  \
395  abnormal          present     present           yes               yes
396    normal       notpresent  notpresent            no                no
397       NaN       notpresent  notpresent            no                no
398    normal              NaN         NaN            no                no
399    normal       notpresent  notpresent            no                no

    Coronary Artery Disease Appetite Pedal Edema Anemia  Target
395                     yes     good         yes    yes     ckd
396                      no     good          no     no  notckd
397                      no     good          no     no  notckd
398                      no     good          no     no  notckd
399                      no     good          no     no     ckd

[5 rows x 25 columns]
After dropping missing values:
   unique_id   Age  Blood Pressure  Blood Glucose Random  Blood Urea  \
0     102677  59.0            70.0                  76.0       186.0
1     109053  64.0            60.0                 106.0        27.0
2     114717  41.0            80.0                 122.0        25.0
3     118191  42.0            70.0                  93.0        32.0
4     118596  74.0            60.0                  88.0        50.0

   Serum Creatinine  Sodium  Potassium  Hemoglobin  Packed Cell Volume  ...  \
0              15.0   135.0        7.6         7.1                22.0  ...
1               0.7   150.0        3.3        14.4                42.0  ...
2               0.8   138.0        5.0        17.1                41.0  ...
3               0.9   143.0        4.7        16.6                43.0  ...
4               0.6   147.0        3.7        17.2                53.0  ...

   Pus Cell  Pus Cell Clumps    Bacteria  Hypertension Diabetes Mellitus  \
0  abnormal       notpresent  notpresent           yes                no
1    normal       notpresent  notpresent            no                no
2    normal       notpresent  notpresent            no                no
3    normal       notpresent  notpresent            no                no
4    normal       notpresent  notpresent            no                no

  Coronary Artery Disease Appetite Pedal Edema Anemia  Target
0                      no     poor         yes    yes     ckd
1                      no     good          no     no  notckd
2                      no     good          no     no  notckd
3                      no     good          no     no  notckd
4                      no     good          no     no  notckd

[5 rows x 25 columns]
     unique_id   Age  Blood Pressure  Blood Glucose Random  Blood Urea  \
148     980291  62.0            70.0                 122.0        42.0
149     991031  30.0            80.0                  89.0        42.0
150     994377  71.0            70.0                  81.0        18.0
151     995177  69.0            70.0                 214.0        96.0
152     996076  57.0            60.0                 105.0        49.0

     Serum Creatinine  Sodium  Potassium  Hemoglobin  Packed Cell Volume  ...  \
148               1.7   136.0        4.7        12.6                39.0  ...
149               0.5   139.0        5.0        16.7                52.0  ...
150               0.8   145.0        5.0        14.7                44.0  ...
151               6.3   120.0        3.9         9.4                28.0  ...
152               1.2   150.0        4.7        15.7                44.0  ...

     Pus Cell  Pus Cell Clumps    Bacteria  Hypertension Diabetes Mellitus  \
148  abnormal       notpresent  notpresent           yes               yes
149    normal       notpresent  notpresent            no                no
150    normal       notpresent  notpresent            no                no
151  abnormal          present     present           yes               yes
152    normal       notpresent  notpresent            no                no

    Coronary Artery Disease Appetite Pedal Edema Anemia  Target
148                      no     good          no     no     ckd
149                      no     good          no     no  notckd
150                      no     good          no     no  notckd
151                     yes     good         yes    yes     ckd
152                      no     good          no     no  notckd

[5 rows x 25 columns]

## Part 3.4: Sort the dataset according to the Labels

In [33]:
# Sort the dataset according to the values in 'Target' column. Make sure reset the indices after sorting
if 'Target' in merged_df.columns:
    merged_df.sort_values(by='Target', inplace=True)
    merged_df.reset_index(drop=True, inplace=True)
else:
    raise ValueError("Target column is missing from the dataset")
# Print the dataset
print(merged_df.head()) 
print(merged_df.tail())

   unique_id   Age  Blood Pressure  Blood Glucose Random  Blood Urea  \
0     102677  59.0            70.0                  76.0       186.0
1     337834  48.0            70.0                 117.0        56.0
2     343710  61.0            80.0                 173.0       148.0
3     349892  59.0            70.0                 424.0        55.0
4     353025  40.0            70.0                 253.0       150.0

   Serum Creatinine  Sodium  Potassium  Hemoglobin  Packed Cell Volume  ...  \
0              15.0   135.0        7.6         7.1                22.0  ...
1               3.8   111.0        2.5        11.2                32.0  ...
2               3.9   135.0        5.2         7.7                24.0  ...
3               1.7   138.0        4.5        12.6                37.0  ...
4              11.9   132.0        5.6        10.9                31.0  ...

   Pus Cell  Pus Cell Clumps    Bacteria  Hypertension Diabetes Mellitus  \
0  abnormal       notpresent  notpresent           yes                no
1  abnormal          present  notpresent           yes                no
2  abnormal       notpresent  notpresent           yes               yes
3  abnormal       notpresent  notpresent           yes               yes
4    normal       notpresent  notpresent           yes               yes

  Coronary Artery Disease Appetite Pedal Edema Anemia Target
0                      no     poor         yes    yes    ckd
1                      no     poor         yes    yes    ckd
2                     yes     poor         yes    yes    ckd
3                     yes     good          no     no    ckd
4                      no     poor         yes     no    ckd

[5 rows x 25 columns]
     unique_id   Age  Blood Pressure  Blood Glucose Random  Blood Urea  \
148     486397  20.0            70.0                 123.0        44.0
149     203466  22.0            60.0                  97.0        18.0
150     482105  44.0            60.0                  95.0        46.0
151     228849  58.0            80.0                 100.0        50.0
152     996076  57.0            60.0                 105.0        49.0

     Serum Creatinine  Sodium  Potassium  Hemoglobin  Packed Cell Volume  ...  \
148               1.0   135.0        3.8        14.6                44.0  ...
149               1.2   138.0        4.3        13.5                42.0  ...
150               0.5   138.0        4.2        15.0                50.0  ...
151               1.2   140.0        3.5        14.0                50.0  ...
152               1.2   150.0        4.7        15.7                44.0  ...

     Pus Cell  Pus Cell Clumps    Bacteria  Hypertension Diabetes Mellitus  \
148    normal       notpresent  notpresent            no                no
149    normal       notpresent  notpresent            no                no
150    normal       notpresent  notpresent            no                no
151    normal       notpresent  notpresent            no                no
152    normal       notpresent  notpresent            no                no

    Coronary Artery Disease Appetite Pedal Edema Anemia  Target
148                      no     good          no     no  notckd
149                      no     good          no     no  notckd
150                      no     good          no     no  notckd
151                      no     good          no     no  notckd
152                      no     good          no     no  notckd

[5 rows x 25 columns]

## Part 3.5: Encoding Categorical data

In this step, we identify and process the categorical columns in the sorted dataset. We map each unique value in these columns to separate "dummy" columns.

For example, the column 'rbc' will be transformed into two columns 'rbc_normal' and 'rbc_abnormal'. If a row's value in 'rbc' is 'normal', the 'rbc_normal' column will be set to 1 and 'rbc_abnormal' will be set to 0.


**Note: Find a correct pandas function to do this **

In [34]:
# Write code here
categorical_columns = ['Red Blood Cells', 'Pus Cell', 'Pus Cell Clumps', 'Bacteria', 'Hypertension', 'Diabetes Mellitus', 'Coronary Artery Disease', 'Appetite', 'Pedal Edema', 'Anemia', 'Target']
merged_df = pd.get_dummies(merged_df, columns=categorical_columns, drop_first=False).astype(int)
# Print the dataset
print(merged_df.head()) 
print(merged_df.tail())

   unique_id  Age  Blood Pressure  Blood Glucose Random  Blood Urea  \
0     102677   59              70                    76         186
1     337834   48              70                   117          56
2     343710   61              80                   173         148
3     349892   59              70                   424          55
4     353025   40              70                   253         150

   Serum Creatinine  Sodium  Potassium  Hemoglobin  Packed Cell Volume  ...  \
0                15     135          7           7                  22  ...
1                 3     111          2          11                  32  ...
2                 3     135          5           7                  24  ...
3                 1     138          4          12                  37  ...
4                11     132          5          10                  31  ...

   Coronary Artery Disease_no  Coronary Artery Disease_yes  Appetite_good  \
0                           1                            0              0
1                           1                            0              0
2                           0                            1              0
3                           0                            1              1
4                           1                            0              0

   Appetite_poor  Pedal Edema_no  Pedal Edema_yes  Anemia_no  Anemia_yes  \
0              1               0                1          0           1
1              1               0                1          0           1
2              1               0                1          0           1
3              0               1                0          1           0
4              1               0                1          1           0

   Target_ckd  Target_notckd
0           1              0
1           1              0
2           1              0
3           1              0
4           1              0

[5 rows x 36 columns]
     unique_id  Age  Blood Pressure  Blood Glucose Random  Blood Urea  \
148     486397   20              70                   123          44
149     203466   22              60                    97          18
150     482105   44              60                    95          46
151     228849   58              80                   100          50
152     996076   57              60                   105          49

     Serum Creatinine  Sodium  Potassium  Hemoglobin  Packed Cell Volume  ...  \
148                 1     135          3          14                  44  ...
149                 1     138          4          13                  42  ...
150                 0     138          4          15                  50  ...
151                 1     140          3          14                  50  ...
152                 1     150          4          15                  44  ...

     Coronary Artery Disease_no  Coronary Artery Disease_yes  Appetite_good  \
148                           1                            0              1
149                           1                            0              1
150                           1                            0              1
151                           1                            0              1
152                           1                            0              1

     Appetite_poor  Pedal Edema_no  Pedal Edema_yes  Anemia_no  Anemia_yes  \
148              0               1                0          1           0
149              0               1                0          1           0
150              0               1                0          1           0
151              0               1                0          1           0
152              0               1                0          1           0

     Target_ckd  Target_notckd
148           0              1
149           0              1
150           0              1
151           0              1
152           0              1

[5 rows x 36 columns]

In the example we went through above, another solution is to have a single column for the binary variable. In the downstream modeling would this be equivalent? What effect would this have if the categorical variable could take more than 2 values? For example, let's say we have a categorical feature that is "type of condiment" that can take 5 separate values and we are trying to predict the rating of a particular sandwich.

Answer: Yes, it would be equivalent and actually take less memory since you can imply one column based on the other, since they can't be both. For example, if we had rbc_normal (true), then you would know that for that row, rbc_abnormal (false) must follow. This wouldn't be possible for something with more than 2 values because you can't imply what value the other one is given a false value in the column. An example with the condiments is if we had one row called c_ketchup, (meaning condiment ketchup) as false, then you wouldn't know whether it was mustard, mayo, ranch, or otherwise.

## Part 3.6 : Remove Outliers from Numerical Columns

Outliers can disproportionately influence the fit of a regression model, potentially leading to a model that does not generalize well therefore it is important that we remove outliers from the numerical columns of the dataset.

For this dataset, we define an outlier to be 3 times the standard deviation from the mean. Drop these outliers from the dataset

In [35]:
# Remove outliers
numerical_columns = ['Age', 'Blood Pressure', 'Blood Glucose Random', 'Blood Urea', 'Serum Creatinine', 'Sodium', 'Potassium', 'Hemoglobin', 'Packed Cell Volume', 'White Blood Cell Count', 'Red Blood Cell Count']
for col in numerical_columns:
    mean = merged_df[col].mean()
    std = merged_df[col].std()
    merged_df = merged_df[(merged_df[col] > mean - 3 * std) & (merged_df[col] < mean + 3 * std)]
# Print the dataset
merged_df.reset_index(drop=True, inplace=True)
print(merged_df.head()) 
print(merged_df.tail())

   unique_id  Age  Blood Pressure  Blood Glucose Random  Blood Urea  \
0     343710   61              80                   173         148
1     397388   63             100                   280          35
2     438182   73              80                   253         142
3     474407   21              90                   107          40
4     475200   64             100                   163          54

   Serum Creatinine  Sodium  Potassium  Hemoglobin  Packed Cell Volume  ...  \
0                 3     135          5           7                  24  ...
1                 3     143          3          13                  40  ...
2                 4     138          5          10                  33  ...
3                 1     125          3           8                  23  ...
4                 7     140          4           7                  26  ...

   Coronary Artery Disease_no  Coronary Artery Disease_yes  Appetite_good  \
0                           0                            1              0
1                           0                            1              1
2                           0                            1              1
3                           1                            0              1
4                           1                            0              1

   Appetite_poor  Pedal Edema_no  Pedal Edema_yes  Anemia_no  Anemia_yes  \
0              1               0                1          0           1
1              0               1                0          1           0
2              0               1                0          1           0
3              0               1                0          0           1
4              0               0                1          1           0

   Target_ckd  Target_notckd
0           1              0
1           1              0
2           1              0
3           1              0
4           1              0

[5 rows x 36 columns]
     unique_id  Age  Blood Pressure  Blood Glucose Random  Blood Urea  \
128     486397   20              70                   123          44
129     203466   22              60                    97          18
130     482105   44              60                    95          46
131     228849   58              80                   100          50
132     996076   57              60                   105          49

     Serum Creatinine  Sodium  Potassium  Hemoglobin  Packed Cell Volume  ...  \
128                 1     135          3          14                  44  ...
129                 1     138          4          13                  42  ...
130                 0     138          4          15                  50  ...
131                 1     140          3          14                  50  ...
132                 1     150          4          15                  44  ...

     Coronary Artery Disease_no  Coronary Artery Disease_yes  Appetite_good  \
128                           1                            0              1
129                           1                            0              1
130                           1                            0              1
131                           1                            0              1
132                           1                            0              1

     Appetite_poor  Pedal Edema_no  Pedal Edema_yes  Anemia_no  Anemia_yes  \
128              0               1                0          1           0
129              0               1                0          1           0
130              0               1                0          1           0
131              0               1                0          1           0
132              0               1                0          1           0

     Target_ckd  Target_notckd
128           0              1
129           0              1
130           0              1
131           0              1
132           0              1

[5 rows x 36 columns]

## Part 3.7 : Normalize the Numerical Columns

Normalizing numerical attributes ensures that all features contribute equally to the model by scaling them to a consistent range, which improves model performance and convergence. It prevents features with larger scales from disproportionately influencing the model's learning process.

In [36]:
# Normalize the all Numerical Attributes in the dataset.
scaler = StandardScaler()
merged_df[numerical_columns] = scaler.fit_transform(merged_df[numerical_columns])
# Print the dataset
print(merged_df.head()) 
print(merged_df.tail())

   unique_id       Age  Blood Pressure  Blood Glucose Random  Blood Urea  \
0     343710  0.810190        0.730553              1.146438    4.014305
1     397388  0.936367        2.776102              3.520558   -0.225995
2     438182  1.567253        0.730553              2.921481    3.789156
3     474407 -1.713353        1.753327             -0.317973   -0.038371
4     475200  0.999456        2.776102              0.924557    0.486976

   Serum Creatinine    Sodium  Potassium  Hemoglobin  Packed Cell Volume  ...  \
0          1.359270 -0.959702   1.538050   -2.973247           -2.905503  ...
1          1.359270  0.448743  -1.101442   -0.408219           -0.590673  ...
2          2.019062 -0.431535   1.538050   -1.690733           -1.603411  ...
3          0.039687 -2.720258  -1.101442   -2.545742           -3.050180  ...
4          3.998437 -0.079424   0.218304   -2.973247           -2.616150  ...

   Coronary Artery Disease_no  Coronary Artery Disease_yes  Appetite_good  \
0                           0                            1              0
1                           0                            1              1
2                           0                            1              1
3                           1                            0              1
4                           1                            0              1

   Appetite_poor  Pedal Edema_no  Pedal Edema_yes  Anemia_no  Anemia_yes  \
0              1               0                1          0           1
1              0               1                0          1           0
2              0               1                0          1           0
3              0               1                0          0           1
4              0               0                1          1           0

   Target_ckd  Target_notckd
0           1              0
1           1              0
2           1              0
3           1              0
4           1              0

[5 rows x 36 columns]
     unique_id       Age  Blood Pressure  Blood Glucose Random  Blood Urea  \
128     486397 -1.776441       -0.292221              0.037036    0.111728
129     203466 -1.650264       -1.314996             -0.539853   -0.863916
130     482105 -0.262316       -1.314996             -0.584229    0.186777
131     228849  0.620924        0.730553             -0.473289    0.336877
132     996076  0.557836       -1.314996             -0.362349    0.299352

     Serum Creatinine    Sodium  Potassium  Hemoglobin  Packed Cell Volume  \
128          0.039687 -0.959702  -1.101442    0.019286           -0.011966
129          0.039687 -0.431535   0.218304   -0.408219           -0.301320
130         -0.620105 -0.431535   0.218304    0.446791            0.856096
131          0.039687 -0.079424  -1.101442    0.019286            0.856096
132          0.039687  1.681133   0.218304    0.446791           -0.011966

     ...  Coronary Artery Disease_no  Coronary Artery Disease_yes  \
128  ...                           1                            0
129  ...                           1                            0
130  ...                           1                            0
131  ...                           1                            0
132  ...                           1                            0

     Appetite_good  Appetite_poor  Pedal Edema_no  Pedal Edema_yes  Anemia_no  \
128              1              0               1                0          1
129              1              0               1                0          1
130              1              0               1                0          1
131              1              0               1                0          1
132              1              0               1                0          1

     Anemia_yes  Target_ckd  Target_notckd
128           0           0              1
129           0           0              1
130           0           0              1
131           0           0              1
132           0           0              1

[5 rows x 36 columns]

## Part 3.8: Remove Unnecessary columns

Are there any columns in this dataset which are not appropriate for modeling and predictions? Which column(s)? Justify their exclusion and remove them

Answer: At this point in the calculations, since each row is considered a unique value and we aren't using these values to track patients, there no real need to have unique id's, and instead we can just opt to use the index values provided. Having the ID's are just needless clutter.

In [37]:
#Remove that column
unnecessary_columns = ['unique_id'] if 'unique_id' in merged_df.columns else []
merged_df.drop(columns=unnecessary_columns, inplace=True)
# Print the dataset
print(merged_df.head()) 
print(merged_df.tail())

        Age  Blood Pressure  Blood Glucose Random  Blood Urea  \
0  0.810190        0.730553              1.146438    4.014305
1  0.936367        2.776102              3.520558   -0.225995
2  1.567253        0.730553              2.921481    3.789156
3 -1.713353        1.753327             -0.317973   -0.038371
4  0.999456        2.776102              0.924557    0.486976

   Serum Creatinine    Sodium  Potassium  Hemoglobin  Packed Cell Volume  \
0          1.359270 -0.959702   1.538050   -2.973247           -2.905503
1          1.359270  0.448743  -1.101442   -0.408219           -0.590673
2          2.019062 -0.431535   1.538050   -1.690733           -1.603411
3          0.039687 -2.720258  -1.101442   -2.545742           -3.050180
4          3.998437 -0.079424   0.218304   -2.973247           -2.616150

   White Blood Cell Count  ...  Coronary Artery Disease_no  \
0                0.519658  ...                           0
1                0.785483  ...                           0
2               -0.366426  ...                           0
3                1.937392  ...                           1
4               -0.233513  ...                           1

   Coronary Artery Disease_yes  Appetite_good  Appetite_poor  Pedal Edema_no  \
0                            1              0              1               0
1                            1              1              0               1
2                            1              1              0               1
3                            0              1              0               1
4                            0              1              0               0

   Pedal Edema_yes  Anemia_no  Anemia_yes  Target_ckd  Target_notckd
0                1          0           1           1              0
1                0          1           0           1              0
2                0          1           0           1              0
3                0          0           1           1              0
4                1          1           0           1              0

[5 rows x 35 columns]
          Age  Blood Pressure  Blood Glucose Random  Blood Urea  \
128 -1.776441       -0.292221              0.037036    0.111728
129 -1.650264       -1.314996             -0.539853   -0.863916
130 -0.262316       -1.314996             -0.584229    0.186777
131  0.620924        0.730553             -0.473289    0.336877
132  0.557836       -1.314996             -0.362349    0.299352

     Serum Creatinine    Sodium  Potassium  Hemoglobin  Packed Cell Volume  \
128          0.039687 -0.959702  -1.101442    0.019286           -0.011966
129          0.039687 -0.431535   0.218304   -0.408219           -0.301320
130         -0.620105 -0.431535   0.218304    0.446791            0.856096
131          0.039687 -0.079424  -1.101442    0.019286            0.856096
132          0.039687  1.681133   0.218304    0.446791           -0.011966

     White Blood Cell Count  ...  Coronary Artery Disease_no  \
128               -1.119597  ...                           1
129               -0.056296  ...                           1
130               -0.144905  ...                           1
131               -0.587946  ...                           1
132                1.051308  ...                           1

     Coronary Artery Disease_yes  Appetite_good  Appetite_poor  \
128                            0              1              0
129                            0              1              0
130                            0              1              0
131                            0              1              0
132                            0              1              0

     Pedal Edema_no  Pedal Edema_yes  Anemia_no  Anemia_yes  Target_ckd  \
128               1                0          1           0           0
129               1                0          1           0           0
130               1                0          1           0           0
131               1                0          1           0           0
132               1                0          1           0           0

     Target_notckd
128              1
129              1
130              1
131              1
132              1

[5 rows x 35 columns]

## Part 3.9: Export the Cleaned Data

Now that you've completed these cleaning steps you should have a pandas dataframe which is much cleaner and ready for modeling. Our final step is to save our work. Export the DataFrame to a two new formats: csv and json.

In [38]:
# Export the dataframe to a new csv file
merged_df.to_csv("cleaned_kidney_disease_data.csv", index=False)
# Export the dataframe to a new json file
merged_df.to_json("cleaned_kidney_disease_data.json", orient='records')

# Part 4: Data conversions with Large Language Models

One powerful use case of ChatGPT (and other generative language models) is cleaning and transforming data. In some cases, these models can directly manipulate loosely structured data that you provide to them into a standard format. In the other cases, you can often prompt the model to create a conversion or extraction script for you in python or Pandas and then run it on your own. 

In this part of the assignment you will prompt 383GPT to explore these capabilities.

## Part 4.1 GPT Data Manipulation

Take the cleaned dataset that you created in part three and output the top 15 rows of that dataset. Then copy the terminal output, open 383gpt and ask it to convert that output to a markdown table. Paste that markdown table in the cell bellow

|    |       age |        bp |        bgr |         bu |        sc |        sod |       pot |      hemo |       pcv |       wbcc |      rbcc |   al |   su |   rbc_abnormal |   rbc_normal |   pc_abnormal |   pc_normal |   pcc_notpresent |   pcc_present |   ba_notpresent |   ba_present |   htn_no |   htn_yes |   dm_no |   dm_yes |   cad_no |   cad_yes |   appet_good |   appet_poor |   pe_no |   pe_yes |   ane_no |   ane_yes |   Target_ckd |   Target_notckd |
|---:|----------:|----------:|-----------:|-----------:|----------:|-----------:|----------:|----------:|----------:|-----------:|----------:|-----:|-----:|---------------:|-------------:|--------------:|------------:|-----------------:|--------------:|----------------:|-------------:|---------:|----------:|--------:|---------:|---------:|----------:|-------------:|-------------:|--------:|---------:|---------:|----------:|-------------:|----------------:|
|  0 |  0.81019  |  0.730553 |  1.14644   |  4.0143    | 1.35927   | -0.959702  |  1.53805  | -2.97325  | -2.9055   |  0.519658  | -1.87278  |    2 |    0 |              1 |            0 |             1 |           0 |                1 |             0 |               1 |            0 |        0 |         1 |       0 |        1 |        0 |         1 |            0 |            1 |       0 |        1 |        0 |         1 |            1 |               0 |
|  1 |  0.936367 |  2.7761   |  3.52056   | -0.225995  | 1.35927   |  0.448743  | -1.10144  | -0.408219 | -0.590673 |  0.785483  | -0.724947 |    2 |    2 |              0 |            1 |             0 |           1 |                1 |             0 |               0 |            1 |        0 |         1 |       1 |        0 |        0 |         1 |            1 |            0 |       1 |        0 |        1 |         0 |            1 |               0 |
|  2 |  1.56725  |  0.730553 |  2.92148   |  3.78916   | 2.01906   | -0.431535  |  1.53805  | -1.69073  | -1.60341  | -0.366426  | -0.724947 |    2 |    0 |              1 |            0 |             1 |           0 |                1 |             0 |               1 |            0 |        0 |         1 |       0 |        1 |        0 |         1 |            1 |            0 |       1 |        0 |        1 |         0 |            1 |               0 |
|  3 | -1.71335  |  1.75333  | -0.317973  | -0.0383712 | 0.0396867 | -2.72026   | -1.10144  | -2.54574  | -3.05018  |  1.93739   | -1.87278  |    4 |    0 |              0 |            1 |             1 |           0 |                0 |             1 |               0 |            1 |        1 |         0 |       1 |        0 |        1 |         0 |            1 |            0 |       1 |        0 |        0 |         1 |            1 |               0 |
|  4 |  0.999456 |  2.7761   |  0.924557  |  0.486976  | 3.99844   | -0.0794236 |  0.218304 | -2.97325  | -2.61615  | -0.233513  | -1.87278  |    4 |    2 |              1 |            0 |             1 |           0 |                1 |             0 |               0 |            1 |        0 |         1 |       0 |        1 |        1 |         0 |            1 |            0 |       0 |        1 |        1 |         0 |            1 |               0 |
|  5 |  0.747101 | -1.315    |  3.69806   | -0.18847   | 0.0396867 | -1.83998   | -1.10144  | -2.97325  | -2.76083  |  3.17791   | -1.87278  |    3 |    1 |              0 |            1 |             1 |           0 |                0 |             1 |               1 |            0 |        0 |         1 |       1 |        0 |        1 |         0 |            0 |            1 |       1 |        0 |        0 |         1 |            1 |               0 |
|  6 |  0.494747 |  1.75333  |  0.170164  |  2.47579   | 3.33865   | -1.66392   |  0.218304 | -2.11824  | -2.18212  | -0.720859  | -1.87278  |    2 |    0 |              1 |            0 |             1 |           0 |                1 |             0 |               1 |            0 |        0 |         1 |       1 |        0 |        1 |         0 |            1 |            0 |       1 |        0 |        1 |         0 |            1 |               0 |
|  7 |  1.3149   | -0.292221 |  2.05615   |  2.06302   | 3.33865   | -3.60054   | -1.10144  | -2.11824  | -2.3268   |  1.53865   | -1.87278  |    4 |    3 |              0 |            1 |             1 |           0 |                0 |             1 |               0 |            1 |        0 |         1 |       0 |        1 |        0 |         1 |            1 |            0 |       0 |        1 |        0 |         1 |            1 |               0 |
|  8 | -0.136138 | -1.315    |  0.924557  |  1.91292   | 1.35927   |  0.0966321 |  0.218304 | -2.11824  | -2.3268   |  2.91208   | -1.87278  |    1 |    0 |              0 |            1 |             0 |           1 |                1 |             0 |               1 |            0 |        0 |         1 |       0 |        1 |        1 |         0 |            1 |            0 |       1 |        0 |        1 |         0 |            1 |               0 |
|  9 |  0.873279 | -0.292221 |  0.0148476 |  0.0366784 | 0.0396867 | -0.783646  |  0.218304 | -0.835723 | -0.73535  | -0.0562963 | -1.87278  |    3 |    0 |              0 |            1 |             1 |           0 |                1 |             0 |               1 |            0 |        0 |         1 |       0 |        1 |        1 |         0 |            1 |            0 |       1 |        0 |        1 |         0 |            1 |               0 |
| 10 |  0.431659 |  0.730553 |  2.05615   |  1.19995   | 1.35927   | -0.607591  |  0.218304 | -1.69073  | -1.45873  | -0.277817  | -1.87278  |    3 |    1 |              0 |            1 |             1 |           0 |                0 |             1 |               0 |            1 |        0 |         1 |       0 |        1 |        1 |         0 |            1 |            0 |       0 |        1 |        1 |         0 |            1 |               0 |
| 11 |  0.999456 | -1.315    |  2.61085   |  0.637075  | 2.01906   | -0.607591  |  1.53805  | -2.11824  | -2.18212  | -0.233513  | -1.87278  |    4 |    1 |              1 |            0 |             1 |           0 |                1 |             0 |               0 |            1 |        0 |         1 |       0 |        1 |        1 |         0 |            0 |            1 |       0 |        1 |        1 |         0 |            1 |               0 |
| 12 |  1.44108  | -1.315    | -0.0739045 |  3.15123   | 2.67885   | -0.783646  |  0.218304 | -1.26323  | -1.31406  |  3.17791   | -0.724947 |    4 |    0 |              0 |            1 |             0 |           1 |                1 |             0 |               1 |            0 |        0 |         1 |       0 |        1 |        1 |         0 |            0 |            1 |       0 |        1 |        1 |         0 |            1 |               0 |
| 13 |  1.44108  | -0.292221 |  2.16709   |  1.53767   | 1.35927   | -1.31181   |  0.218304 | -1.69073  | -1.60341  | -1.07529   | -1.87278  |    3 |    0 |              0 |            1 |             1 |           0 |                0 |             1 |               0 |            1 |        0 |         1 |       0 |        1 |        0 |         1 |            1 |            0 |       1 |        0 |        1 |         0 |            1 |               0 |
| 14 |  0.684013 |  0.730553 |  4.03088   | -0.225995  | 0.0396867 | -3.24843   | -1.10144  | -1.69073  | -1.31406  |  1.27283   | -0.724947 |    1 |    0 |              1 |            0 |             0 |           1 |                1 |             0 |               1 |            0 |        1 |         0 |       0 |        1 |        1 |         0 |            0 |            1 |       1 |        0 |        1 |         0 |            1 |               0 |

## Part 4.2 GPT Pandas Prompting

In this section, you will prompt 383GPT to write pandas code manipulations for you.

After working with this data for awhile, we realized we're starting to forget the meanings of the abbreviated column names. Let's ask 383GPT to fix this for us. First, navigate to the [UCI dataset overview](https://archive.ics.uci.edu/dataset/336/chronic+kidney+disease) and copy the abbrevation to name mapping. Then, go to 383GPT and instruct the LLM to provide you with a pandas script to apply this renaming to all the columns of your dataset. Paste that code below and make any adjustments necessary to run it in your notebook.

** Caution: ** while language models can perform data conversions they also can * hallucinate * during this process, particularly for bigger datasets. Reflect on this below, how could you mitigate data conversion hallucinations from LLM conversions?

Generally speaking, the most important part is proof-reading the data once its readable. GPT and LLMS in general have alternative outputs that they can choose from which might be able to fit your ideal outcome. Alternatively, you can use an LLM that is explicitly designed for this type of output, such as an AI that is meant to convert plaintext to markdown tables.

In [ ]:
# Code to rename all the columns in the dataset
column_mappings = {
    "age": "Age",
    "bp": "Blood Pressure",
    "sg": "Specific Gravity",
    "al": "Albumin",
    "su": "Sugar",
    "rbc": "Red Blood Cells",
    "pc": "Pus Cell",
    "pcc": "Pus Cell Clumps",
    "ba": "Bacteria",
    "bgr": "Blood Glucose Random",
    "bu": "Blood Urea",
    "sc": "Serum Creatinine",
    "sod": "Sodium",
    "pot": "Potassium",
    "hemo": "Hemoglobin",
    "pcv": "Packed Cell Volume",
    "wbcc": "White Blood Cell Count",
    "rbcc": "Red Blood Cell Count",
    "htn": "Hypertension",
    "dm": "Diabetes Mellitus",
    "cad": "Coronary Artery Disease",
    "appet": "Appetite",
    "pe": "Pedal Edema",
    "ane": "Anemia",
}
# categorical_df.rename(columns=column_mappings, inplace=True)
# numerical_df.rename(columns=column_mappings, inplace=True)
# As a note to the graders, 383GPT scanned the "additional information 
# section" and 2 were unaccounted for since in that section it was 
# mentioned that the column name was "rc" but in the dataset it was 
# "rbcc" so I changed it in the mapping to "rbcc" to match the dataset. 
# The same was done for "wc" which was "wbcc" in the dataset. 
# Additionally, class was listed as a category but wasn't a column. 
# Class was removed from the column_mappings dictionary and target was 
# added. This code was actually ran in part 1 of the assignment so it 
# would apply to everything.

## Part 4.3 Augmenting our skills with prompting

In addition, we can also use 383GPT to convert our data manipulation operations between different data manipulation languages and libraries. For example let's prompt 383GPT to convert the following SQL query to a pandas query.

**SQL Query**
```sql
SELECT Target, COUNT(*) AS count
FROM your_table_name
GROUP BY Target;
```

Prompt 383GPT to convert this to a pandas query. Run this query below, then describe what it does. (If you're not familiar with SQL that is okay you need to only comment on the final resulting output.)

In [ ]:
#Converted SQL to Pandas code
result = merged_df.groupby('Target_ckd').size().reset_index(name='count')
print(result)
#We were told to change the original code to the target column is 
# now "Target_ckd" so I changed it in the code above.

   Target_ckd  count
0           0    111
1           1     22

*Describe what the above code does here* The code is essentially a nice summary of how many people within the chart had or didn't have Chronic Kidney Disease. It lists out how many did and didn't have it in a 2x3 formatted table.